version: '3.7'

volumes:
  faktory-data:
    driver: local

services:
  client:
    build:
      context: client
    volumes:
      - /tmp/uploads:/app/uploads
    environment:
      FAKTORY_HOST: host.docker.internal
    depends_on:
      - faktory

  server:
    build:
      context: server
    volumes:
      - /tmp/uploads:/app/uploads
    ports:
      - 8080:8080
    environment:
      FAKTORY_HOST: host.docker.internal
    depends_on:
      - faktory

  faktory:
    image: contribsys/faktory:latest
    volumes:
      - faktory-data:/var/lib/faktory
    ports:
      - 7419:7419
      - 7420:7420
